---
title: "orthomcl-gene-exploration"
author: "Bin He"
date: "5/28/2020"
output: 
  html_notebook: 
    code_folding: hide
    theme: paper
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_data_library, echo=FALSE}
load("orthomcl-v5-mapping-analysis-cache.RData")
# install the package if not already available
if (!requireNamespace("tidyverse", quietly = TRUE))
    install.packages("tidyverse")
if (!requireNamespace("rentrez", quietly = TRUE))
    install.packages("rentrez")
if (!requireNamespace("kableExtra", quietly = TRUE))
    install.packages("kableExtra")

require(tidyverse, quietly = TRUE)
require(rentrez, quietly = TRUE)
require(kableExtra, quietly = TRUE)
```

```{r extract_cdd_fct, echo=FALSE}
get_cdd <- function(pid){
  hit <- entrez_link(dbfrom = "protein", id = pid, db = "cdd")
  # the returned objects will contain multiple links to different
  # cdd display modes:
  # 1. concise: shows only the best scoring model, in each hit category
  # 2. standard: shows the best scorning model from each source in each hit category (some redundancy)
  # 3. full: shows all domain models in each hit category
  cdd.sum <- entrez_summary(db = "cdd", id = hit$links$protein_cdd_summary)
  cdd.res <- extract_from_esummary(cdd.sum, c("accession", "subtitle", "abstract"), simplify = TRUE)
  print(cdd.res)
}
```

Here are all the orthogroups that contain at least two of the predicted adhesins in all species. The numbers in columns 2-4 represent the number of genes in each species (for _C. auris_, I took the **median** values of the three strains).
```{r list_all_ogs, echo=FALSE}
frv.mcl5.sum %>% 
  filter(total > 2) %>% 
  select(-total) %>% 
  paged_table() %>% 
  kable() %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```

Build a Shiny app to allow the user to interactively select the orthogroup and gene to learn more about their annotation.
```{r interactive_exploration, echo = FALSE}
inputPanel(
  # let the user choose the orthogroup to display
  selectInput(inputId = "gid", label = "Please select the orthogroup", choices = frv.mcl5.sum$group_id),
  selectInput(inputId = "pid", label = "Please select the protein ID", choices = frv.mapped5$protein_id, selected = "XP_718077.1")
  # let the user provide the protein_id
  #textInput(inputId = "pid", label = "Please provide the protein ID", value = "XP_718077.1")
)

observe({
  updateSelectInput(session, "pid", choices = frv.mapped5$protein_id[frv.mapped5$orthomcl_group_id == input$gid])
}
)

fluidPage(
  titlePanel("Conserved Domain Database"),
  fluidRow(
    column(5,
           renderTable({
             members <- frv.mapped5 %>% 
               filter(orthomcl_group_id == input$gid) %>% 
               pull(protein_id)
             
             gene.sum %>% 
               filter(protein_id %in% members) %>% 
               select(Strain, protein_id, gene_name)
           })
    ),
    column(7,
           # show the gene table based on the orthogroup choice
           renderPrint({
             get_cdd(pid = input$pid)
           }) 
    )       
  ) 
)
```

